#!/bin/env bash


function install_packages {

    local manually_installed=(
        'curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash'
    );

    for package in "${manually_installed[@]}"
    do
        ${package}
    done
}

function install_vim_package {

    function install_pathogen {
        mkdir -p ~/.vim/autoload ~/.vim/bundle && \
        curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
    }

    readonly vim_plugins=(
        "https://github.com/scrooloose/nerdtree.git"
        "https://github.com/Xuyuanp/nerdtree-git-plugin.git"
        "https://github.com/airblade/vim-gitgutter.git"
        "https://github.com/editorconfig/editorconfig-vim.git"
        "https://github.com/mxw/vim-jsx.git"
        "https://github.com/flowtype/vim-flow"
    )

    function install_vim_plugins {
        for plugin in "${vim_plugins[@]}"
        do
            local plugin_name=`echo "${plugin}" | cut -d/ -f5 | cut -d. -f1`
            git clone "${plugin}" "$HOME/.vim/bundle/${plugin_name}"
        done
    }

    function run {
        install_pathogen
        install_vim_plugins
    }

    run
}

function run {
    install_vim_package
}


run
