#!/bin/env bash


function install_packages {

    local manually_installed=(
        'curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash'
    );



    for package in "${manually_installed[@]}"
    do
        ${package}
    done
}