#!/bin/env bash

# check if user is root
if [ "$(id -u)" != 0 ]
then
    echo "Please log in as root"
    echo -e "\e[31mRead the code before running!\n"

    exit 1
fi

USER_HOME_DIRECTORY=$(who | awk '{ print "/home/"$1 }')

function initialise_frapper {
    mkdir -p $USER_HOME_DIRECTORY/.frapper/vendor/{bash,tmux}
}

# Copy over the dotfiles
function install_dotfiles {
    local INSTALLER_LOCATION=$(dirname "$(readlink -f "$0")")
    cp -r "$INSTALLER_LOCATION/bash/" $USER_HOME_DIRECTORY/.frapper/
    cp "$INSTALLER_LOCATION/tmux/.tmux.conf.local" $USER_HOME_DIRECTORY/.frapper/vendor/tmux
}

# Download external tools/plugins
function install_plugins {

    local python_plugins=(
        'pygments'
    )

    local bash_plugins=(
        'curl https://raw.githubusercontent.com/shyiko/commacd/master/commacd.bash -o commacd.bash'
    )

    local tmux_plugins=(
        'curl https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf -o .tmux.conf'

    for plugin in "${python_plugins[@]}"
    do
        pip install "${plugin}"
    done

    cd $USER_HOME_DIRECTORY/.frapper/vendor/bash
    for plugin in "${bash_plugins[@]}"
    do
       sudo ${plugin}
    done

    cd $USER_HOME_DIRECTORY/.frapper/vendor/tmux
    for plugin in "${tmux_plugin[@]}"
    do
        sudo "${plugin}"
    done
}

function run {
    initialise_frapper
    install_dotfiles
    install_plugins
}

run
