#!/bin/env bash

function install_vim_packages {

    function prep_vim_environment {
        mkdir -p $HOME/.vim/undo
        cp -r ./home/.vim/* $HOME/.vim/
    }

    function install_pathogen {
        mkdir -p $HOME/.vim/autoload ~/.vim/bundle && \
        curl -LSso $HOME/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
    }

    function install_vim_plugins {
        source ./vim/plugins
        for plugin in "${vim_plugins[@]}"
        do
            local plugin_name=`echo "${plugin}" | cut -d/ -f5 | cut -d. -f1`
            git clone "${plugin}" "$HOME/.vim/bundle/${plugin_name}"
        done

        cd $HOME/.vim/bundle/vimproc.vim
        make
        cd -
    }

    function run {
        prep_vim_environment
        install_pathogen
        install_vim_plugins
    }

    run
}
