#!/usr/env bash

readonly vim_plugins=(
    "https://github.com/scrooloose/nerdtree.git"
    "https://github.com/Xuyuanp/nerdtree-git-plugin.git"
    "https://github.com/ctrlpvim/ctrlp.vim.git"
    "https://github.com/airblade/vim-gitgutter.git"
    "https://github.com/editorconfig/editorconfig-vim.git"
    "https://github.com/mxw/vim-jsx.git"
    "https://github.com/flowtype/vim-flow"
    "https://github.com/tpope/vim-surround.git"
    "https://github.com/bling/vim-airline"
    "https://github.com/m2mdas/phpcomplete-extended"
    "https://github.com/Shougo/vimproc.vim.git"
)
