#!/bin/env bash

function install_snaps {
    source ./snaps/packages

    for package_index in "${!snap_packages[@]}"
    do
        if [ "${is_a_classic_package}" = true ]
        then
            snap install "${package} --classic"
        else
            snap install "${package}"
        fi
    done
}
