#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# Go get all the imports
for file in $(find -L ${DIR}/{flags,partials,plugins,user,aliases} -type f)
do
    source $file
done

# Check if tmux is loaded and then loaded
if command -v tmux > /dev/null; then
  [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
fi
