#!/bin/env bash

LIGHT_PURPLE="\[\033[38;5;13m\]"
CYAN="\[\033[38;5;6m\]"
GREEN="\[\033[38;5;28m\]"
WHITE="\[\033[38;5;15m\]"

git_info() {
    git_status="`git status -unormal 2>&1`"
    if ! [[ "$git_status" =~ Not\ a\ git\ repo ]]; then
        echo -e "\e[96m@\e[95m$(git rev-parse --abbrev-ref HEAD)"
    fi
}

USERNAME="${LIGHT_PURPLE}\u"
HOSTNAME="${CYAN}\h"
DIRECTORY="${GREEN}\w"
GIT_META_DATA="\n$(git_info)"
USER_PROMPT="\n${CYAN}> ${WHITE}"

export PS1="${USERNAME}@${HOSTNAME} ${DIRECTORY}${GIT_META_DATA}${USER_PROMPT}"



unset LIGHT_PURPLE
unset CYAN
unset GREEN
unset WHITE
unset USERNAME
unset HOSTNAME
unset DIRECTORY
unset GIT_META_DATA
unset USER_PROMPT
