#!/usr/env bash

readonly solus_packages=(
    keepassxc
    owncloud-client
    gnome-tweak-too
    steam
    digikam
    virt-manager
    ghostwriter
    gimp
    inkscape
    calibre
    # Drivers
    nvidia-glx-driver-current
    nvidia-glx-driver-32bit
    # tools
    xclip
    vim
    tmux
    tilda
    git
    clipit
    heroku
    #Budgie
    budgie-screenshot-applet
    budgie-calendar-applet
    arc-gtk-theme
    arc-icon-theme
    flat-plat-gtk-theme
    sardi-icons
)

